name: Node.js CI

on:
  release:
    types: [created]
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Configure .npmrc for npm registry
        run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=\${{secrets.TOKEN_NPM_PSO}}" >> ~/.npmrc
          echo "@your-github-username:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=\${{secrets.GITHUB_TOKEN}}" >> ~/.npmrc
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Configure .npmrc for npm registry
        run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=\${{secrets.TOKEN_NPM_PSO}}" >> ~/.npmrc
          echo "@your-github-username:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=\${{secrets.GITHUB_TOKEN}}" >> ~/.npmrc
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_NPM_PSO}}

